Add transitive reduction algorithm
ZigRazor/CXXGraph pull request #304
Opened 2023-05-24 06:26 UTC by nrkramer

*A good pull request has the following information:*
- Addresses https://github.com/ZigRazor/CXXGraph/issues/273
- Adds the transitive reduction algorithm and supporting test
- @mentions of the person or team responsible for reviewing proposed changes. ( optional ) 
  - @nrkramer

2023-05-24 06:30 UTC, nrkramer commented on include/Graph/Graph.hpp
> +      [&nodeUserId](auto node) { return node->getUserId() == nodeUserId; });
Automatically done by clang-format

2023-05-24 06:31 UTC, nrkramer commented on include/Graph/Graph.hpp
> +      [&nodeUserId](auto node) { return node->getUserId() == nodeUserId; });
Automatically done by clang-format

2023-05-24 06:31 UTC, nrkramer commented on include/Graph/Graph.hpp
> +  });
Automatically done by clang-format

2023-05-24 06:31 UTC, nrkramer commented on include/Graph/Graph.hpp
> +    return -1;
Automatically done by clang-format

2023-05-24 06:31 UTC, nrkramer commented on include/Graph/Graph.hpp
> +    return -1;
Automatically done by clang-format

2023-05-24 08:10 UTC, ZigRazor requested changes
Do you can check if is possible to eliminate at least the "violations" reported by cppcheck?

2023-05-24 08:11 UTC, ZigRazor commented on include/Graph/Graph.hpp
> +      [&nodeUserId](auto node) { return node->getUserId() == nodeUserId; });
ok

2023-05-24 08:11 UTC, ZigRazor commented on include/Graph/Graph.hpp
> +    return -1;
ok

2023-05-24 08:11 UTC, ZigRazor commented on include/Graph/Graph.hpp
> +    return -1;
ok

2023-05-24 08:11 UTC, ZigRazor commented on include/Graph/Graph.hpp
> +  });
ok

2023-05-25 05:17 UTC, nrkramer commented
> Do you can check if is possible to eliminate at least the "violations" reported by cppcheck?

I've fixed a few of the "violations". Some of them seem intended for C, such as MISRA 17.8, as reference parameter modification is bread-and-butter in C++ (in C++, programmers use `const` to denote that the reference should not be modified in the function body).

Some of the other violations, such as MISRA 15.5, are necessary as optimizations. Early return from function is common practice to speed up function calls, and refractoring the function to support leaving loops quickly would result in code that is difficult to understand.

I've dismissed the violations on code in which this PR is not concerned, as it is irrelevant to the PR.

2023-05-25 06:51 UTC, ZigRazor approved these changes
Good Job!

2023-05-25 06:52 UTC, merged