include <algorithm> for gcc 14 compilation errors
ZigRazor/CXXGraph pull request #428
Opened 2024-05-05 17:50 UTC by toge

I met a lot of compilation errors on gcc 14:
It seems to be caused by a lack of including <algorithm> header.
This PR is fixed this problem.

Please review it.

<details>
<summary>CXXGraph 3.1.0 compilation errors on gcc 14</summary>

In file included from include/CXXGraph/Graph/Graph.h:23,
                 from include/CXXGraph/CXXGraph.hpp:11,
                 from test_package.cpp:3:
include/CXXGraph/Graph/Graph_impl.hpp: In member function ‘virtual void CXXGraph::Graph<T>::setNodeData(const std::string&, T)’:
include/CXXGraph/Graph/Graph_impl.hpp:316:22: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
  316 |   auto nodeIt = std::find_if(
      |                      ^~~~~~~
      |                      find
include/CXXGraph/Graph/Graph_impl.hpp: In member function ‘virtual std::shared_ptr<std::vector<CXXGraph::Node<T> > > CXXGraph::Graph<T>::eulerianPath() const’:
include/CXXGraph/Graph/Graph_impl.hpp:465:27: error: ‘max_element’ is not a member of ‘std’; did you mean ‘tuple_element’?
  465 |   auto firstNodeIt = std::max_element(
      |                           ^~~~~~~~~~~
      |                           tuple_element
include/CXXGraph/Graph/Graph_impl.hpp: In member function ‘virtual const std::vector<CXXGraph::Node<T> > CXXGraph::Graph<T>::graph_slicing(const CXXGraph::Node<T>&) const’:
include/CXXGraph/Graph/Graph_impl.hpp:775:29: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
  775 |   auto start_node_it = std::find_if(
      |                             ^~~~~~~
      |                             find
include/CXXGraph/Graph/Graph_impl.hpp:785:14: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
  785 |     if (std::find_if(C.begin(), C.end(), [node](const Node<T> nodeC) {
      |              ^~~~~~~
      |              find
include/CXXGraph/Graph/Graph_impl.hpp:800:14: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
  800 |     if (std::find_if(M.begin(), M.end(), [nodeC](const Node<T> nodeM) {
      |              ^~~~~~~
      |              find
In file included from include/CXXGraph/Graph/Graph.h:26:
include/CXXGraph/Graph/Algorithm/BellmanFord_impl.hpp: In member function ‘virtual const CXXGraph::BellmanFordResult CXXGraph::Graph<T>::bellmanford(const CXXGraph::Node<T>&, const CXXGraph::Node<T>&) const’:
include/CXXGraph/Graph/Algorithm/BellmanFord_impl.hpp:36:30: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
   36 |   auto source_node_it = std::find_if(
      |                              ^~~~~~~
      |                              find
include/CXXGraph/Graph/Algorithm/BellmanFord_impl.hpp:44:30: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
   44 |   auto target_node_it = std::find_if(
      |                              ^~~~~~~
      |                              find
In file included from include/CXXGraph/Graph/Graph.h:27:
include/CXXGraph/Graph/Algorithm/BestFirstSearch_impl.hpp: In member function ‘virtual CXXGraph::BestFirstSearchResult<T> CXXGraph::Graph<T>::best_first_search(const CXXGraph::Node<T>&, const CXXGraph::Node<T>&) const’:
include/CXXGraph/Graph/Algorithm/BestFirstSearch_impl.hpp:40:30: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
   40 |   auto source_node_it = std::find_if(
      |                              ^~~~~~~
      |                              find
include/CXXGraph/Graph/Algorithm/BestFirstSearch_impl.hpp:48:30: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
   48 |   auto target_node_it = std::find_if(
      |                              ^~~~~~~
      |                              find
include/CXXGraph/Graph/Algorithm/BestFirstSearch_impl.hpp: In member function ‘virtual const std::vector<CXXGraph::Node<T> > CXXGraph::Graph<T>::concurrency_breadth_first_search(const CXXGraph::Node<T>&, size_t) const’:
include/CXXGraph/Graph/Algorithm/BestFirstSearch_impl.hpp:111:29: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
  111 |   auto start_node_it = std::find_if(
      |                             ^~~~~~~
      |                             find
In file included from include/CXXGraph/Graph/Graph.h:29:
include/CXXGraph/Graph/Algorithm/BreadthFirstSearch_impl.hpp: In member function ‘virtual const std::vector<CXXGraph::Node<T> > CXXGraph::Graph<T>::breadth_first_search(const CXXGraph::Node<T>&) const’:
include/CXXGraph/Graph/Algorithm/BreadthFirstSearch_impl.hpp:36:29: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
   36 |   auto start_node_it = std::find_if(
      |                             ^~~~~~~
      |                             find
In file included from include/CXXGraph/Graph/Graph.h:31:
include/CXXGraph/Graph/Algorithm/CycleDetection_impl.hpp: In member function ‘virtual bool CXXGraph::Graph<T>::containsCycle(CXXGraph::T_EdgeSet<T>*) const’:
include/CXXGraph/Graph/Algorithm/CycleDetection_impl.hpp:122:16: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
  122 |       if (std::find_if((*subset).begin(), (*subset).end(), nodeExists) ==
      |                ^~~~~~~
      |                find
include/CXXGraph/Graph/Algorithm/CycleDetection_impl.hpp: In member function ‘virtual bool CXXGraph::Graph<T>::containsCycle(CXXGraph::shared<const std::unordered_set<std::shared_ptr<const CXXGraph::Edge<T> >, CXXGraph::edgeHash<T> > >) const’:
include/CXXGraph/Graph/Algorithm/CycleDetection_impl.hpp:148:16: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
  148 |       if (std::find_if((*subset).begin(), (*subset).end(), nodeExists) ==
      |                ^~~~~~~
      |                find
In file included from include/CXXGraph/Graph/Graph.h:32:
include/CXXGraph/Graph/Algorithm/DepthFirstSearch_impl.hpp: In member function ‘virtual const std::vector<CXXGraph::Node<T> > CXXGraph::Graph<T>::depth_first_search(const CXXGraph::Node<T>&) const’:
include/CXXGraph/Graph/Algorithm/DepthFirstSearch_impl.hpp:36:29: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
   36 |   auto start_node_it = std::find_if(
      |                             ^~~~~~~
      |                             find
In file included from include/CXXGraph/Graph/Graph.h:33:
include/CXXGraph/Graph/Algorithm/Dial_impl.hpp: In member function ‘virtual const CXXGraph::DialResult CXXGraph::Graph<T>::dial(const CXXGraph::Node<T>&, int) const’:
include/CXXGraph/Graph/Algorithm/Dial_impl.hpp:36:30: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
   36 |   auto source_node_it = std::find_if(
      |                              ^~~~~~~
      |                              find
include/CXXGraph/Graph/Algorithm/Dial_impl.hpp:112:23: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
  112 |       auto u_i = std::find_if(
      |                       ^~~~~~~
      |                       find
include/CXXGraph/Graph/Algorithm/Dial_impl.hpp:119:23: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
  119 |       auto v_i = std::find_if(
      |                       ^~~~~~~
      |                       find
In file included from include/CXXGraph/Graph/Graph.h:34:
include/CXXGraph/Graph/Algorithm/Dijkstra_impl.hpp: In member function ‘virtual const CXXGraph::DijkstraResult CXXGraph::Graph<T>::dijkstra(const CXXGraph::Node<T>&, const CXXGraph::Node<T>&) const’:
include/CXXGraph/Graph/Algorithm/Dijkstra_impl.hpp:34:30: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
   34 |   auto source_node_it = std::find_if(
      |                              ^~~~~~~
      |                              find
include/CXXGraph/Graph/Algorithm/Dijkstra_impl.hpp:43:30: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
   43 |   auto target_node_it = std::find_if(
      |                              ^~~~~~~
      |                              find
include/CXXGraph/Graph/Algorithm/Dijkstra_impl.hpp:145:10: error: ‘reverse’ is not a member of ‘std’
  145 |     std::reverse(resul [...]

2024-05-06 06:17 UTC, ZigRazor requested changes

2024-05-06 06:17 UTC, ZigRazor commented on include/CXXGraph/Graph/Graph_decl.h
> +#include <algorithm>
Why introduce `<algorithm>` in `Graph_decl.h`? Maybe is better introduce it when it needed

2024-05-06 06:21 UTC, nolankramer requested changes
Please only `#include <algorithm>` in the `*_impl.hpp` files where it is needed.

2024-05-12 15:33 UTC, toge commented
@ZigRazor  @nolankramer 
I update this PR to include <algorithm> only on *_impl.hpp.
Could you review it again?

2024-05-13 05:59 UTC, ZigRazor approved these changes
Good! thank you

2024-05-13 12:35 UTC, nolankramer approved these changes

2024-06-20 09:35 UTC, merged